version: "3.8"

services:

  server:
    image: node:12
    command: sh -c "npm install && node server/index.js"
    working_dir: /reviews-api
    ports:
      - 3000:3000
    volumes:
      - ./:/reviews-api

  db:
    image: postgres
    restart: always
    volumes:
      - reviews-postgres-data:/var/lib/postgres/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: reviewsData
    ports:
      - '5432:5432'

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  reviews-postgres-data: